# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=2500)),
                ('price', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Jumia phones by Price listing',
            },
        ),
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
