# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0026_auto_20190327_2239'),
        ('scrapit', '0002_auto_20190328_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlxPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('link', models.URLField()),
                ('image', models.TextField(null=True)),
                ('url', models.URLField()),
                ('checker_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
                ('phone_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapit.PhoneWebsite')),
            ],
        ),
    ]
