# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0026_auto_20190327_2239'),
        ('scrapit', '0003_olxphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PigiaWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('scraper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper')),
                ('scraper_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
        ),
        migrations.RenameModel(
            old_name='PhoneWebsite',
            new_name='OlxWebsite',
        ),
        migrations.RenameModel(
            old_name='Phone',
            new_name='PigiaPhone',
        ),
        migrations.AlterField(
            model_name='pigiaphone',
            name='phone_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapit.PigiaWebsite'),
        ),
    ]
